name: check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

jobs:
  cairo-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Setup Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Install cairo-lint
        run: cargo install scarb-cairo-lint --git https://github.com/keep-starknet-strange/cairo-lint

      - uses: asdf-vm/actions/install@v3
      - run: scarb cairo-lint
      - run: scarb cairo-lint --fix

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: scarb test
